{
 "title": "dash-forum-api",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API USE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HEAP USED",
     "type": "gauge",
     "description": "Memória heap utilizada",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\",job=\"app-forum-api\",area=\"heap\"})*100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\",job=\"app-forum-api\",area=\"heap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU UTILIZATION",
     "type": "timeseries",
     "description": "Utilização de CPU",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "System CPU usage"
      },
      {
       "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "NO HEAP USED",
     "type": "gauge",
     "description": "Memória no-heap utilizada",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\",job=\"app-forum-api\",area=\"nonheap\"})*100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\",job=\"app-forum-api\",area=\"nonheap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LOAD AVAREGA",
     "type": "timeseries",
     "description": "Média de uso de CPU",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{application=\"$application\",instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "Load avarega[1m]"
      },
      {
       "expr": "system_cpu_count{application=\"$application\",instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "CPU core size"
      }
     ]
    }
   ]
  },
  {
   "title": "RED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "REQUESTS COUNT",
     "type": "timeseries",
     "description": "Numero de requisições por endpoint no ultimo minuto",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/topicos\"}[1m]))",
       "legendFormat": "/topicos"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/topicos/{id}\"}[1m]))",
       "legendFormat": "/topicos/{id}"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/auth\"}[1m]))",
       "legendFormat": "/auth"
      }
     ]
    },
    {
     "title": "ERROR 500",
     "type": "stat",
     "description": "Numero de erro 500 no ultimo minuto",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TOTAL REQUESTS",
     "type": "stat",
     "description": "Numero de requisições no ultimo minuto",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVERAGE REQUEST RURATION",
     "type": "timeseries",
     "description": "Duração média de requisições do ultimo minuto",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\",uri=\"/topicos\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\",uri=\"/topicos\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\",uri=\"/topicos/{id}\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\",uri=\"/topicos/{id}\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\",uri=\"/auth\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\",uri=\"/auth\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "ERROR RATE",
     "type": "timeseries",
     "description": "Taxa de Erros nos ultimos 5 minutos",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\" }[5m]))",
       "legendFormat": "500"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\" }[5m]))",
       "legendFormat": "400"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\" }[5m]))",
       "legendFormat": "404"
      }
     ]
    },
    {
     "title": "LATENCY AVAREGA",
     "type": "timeseries",
     "description": "Latencia media por minuto",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[1m])) by (le)) ",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[1m])) by (le)) ",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[1m])) by (le)) ",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[1m])) by (le)) ",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\",uri!=\"/actuator/prometheus\"}[1m])) by (le)) ",
       "legendFormat": "25%"
      }
     ]
    },
    {
     "title": "RESPONSE TIME",
     "type": "timeseries",
     "description": "Tempo de resposta no ultimo minuto",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\",job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\",job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{uri}}{{method}}{{status}}"
      }
     ]
    },
    {
     "title": "MAX REQUEST DURATION",
     "type": "timeseries",
     "description": "Duração maxima de uma requisição",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\",job=\"app-forum-api\", status=\"200\"}",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API BASIC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPTIME",
     "type": "stat",
     "description": "API Uptime",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "USERLOGGED",
     "type": "stat",
     "description": "Usuario logados",
     "gridPos": { "h": 4, "w": 8, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_success_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CONNECTION STATC",
     "type": "timeseries",
     "description": "Estado das conexões com o database",
     "gridPos": { "h": 12, "w": 11, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "acive"
      },
      {
       "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "idle"
      },
      {
       "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "DB CONNECTION TIMEOUT",
     "type": "stat",
     "description": "Conexões com o database em timeout",
     "gridPos": { "h": 4, "w": 8, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\",job=\"app-forum-api\",pool=\"$pool\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "START TIME",
     "type": "stat",
     "description": "START TIME",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AUTHERROS",
     "type": "stat",
     "description": "Erros de autenticação no ultimo minuto",
     "gridPos": { "h": 4, "w": 8, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_error_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WARN & ERROR LOG",
     "type": "timeseries",
     "description": "Warnings e erros logados nos íltimos 5 minutos",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "shot" } },
     "targets": [
      {
       "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"warn\"}[5m])",
       "legendFormat": "{{level}}"
      },
      {
       "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"error\"}[5m])",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  }
 ]
}